// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "Hero_standing_right":return img`
. . . . . . f f f f f f . . . . 
. . . . f f e e e e f 2 f . . . 
. . . f f e e e e f 2 2 2 f . . 
. . . f e e e f f e e e e f . . 
. . . f f f f e e 2 2 2 2 e f . 
. . . f e 2 2 2 f f f f e 2 f . 
. . f f f f f f f e e e f f f . 
. . f f e 4 4 e b f 4 4 e e f . 
. . f e e 4 d 4 1 f d d e f . . 
. . . f e e e 4 d d d d f . . . 
. . . . f f e e 4 4 4 e f . . . 
. . . . . 4 d d e 2 2 2 f . . . 
. . . . . e d d e 2 2 2 f . . . 
. . . . . f e e f 4 5 5 f . . . 
. . . . . . f f f f f f . . . . 
. . . . . . . f f f . . . . . . 
`;
            case "image1":
            case "Hero_standing_left":return img`
. . . . f f f f f f . . . . . . 
. . . f 2 f e e e e f f . . . . 
. . f 2 2 2 f e e e e f f . . . 
. . f e e e e f f e e e f . . . 
. f e 2 2 2 2 e e f f f f . . . 
. f 2 e f f f f 2 2 2 e f . . . 
. f f f e e e f f f f f f f . . 
. f e e 4 4 f b e 4 4 e f f . . 
. . f e d d f 1 4 d 4 e e f . . 
. . . f d d d d 4 e e e f . . . 
. . . f e 4 4 4 e e f f . . . . 
. . . f 2 2 2 e d d 4 . . . . . 
. . . f 2 2 2 e d d e . . . . . 
. . . f 5 5 4 f e e f . . . . . 
. . . . f f f f f f . . . . . . 
. . . . . . f f f . . . . . . . 
`;
            case "image3":
            case "myImage":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "Uwu22e:N^{Q7/[BL~JB*":
            case "Enemy":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.....ffff111111bf.......
....fc111cdb1bdfff......
....f1b1bcbfbfc111cf....
....fbfbfbffff1b1b1f....
.........fffffffbfbf....
..........fffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image5":
            case "Hitbox":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . 1 . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image6":
            case "DashSpriteRIGHT":return img`
.......ff...............
....ffff2ff.............
..ffeeeef2ff............
.ffeeeeef22ff...........
.feeeeffeeeef...........
.fffffee2222ef..........
fffe222ffffe2f..........
ffffffffeeefff..........
fefe44ebf44eef..........
.fee4d4bfddef...........
..feee4dddee.c..........
...f2222eeddeccccccc....
...f444e44ddecddddd.....
...fffffeeee.ccccc......
..ffffffff...c..........
..fff..ff...............
........................
........................
........................
........................
........................
........................
........................
........................
`;
            case "image7":
            case "DashSpriteLeft":return img`
...............ff.......
.............ff2ffff....
............ff2feeeeff..
...........ff22feeeeeff.
...........feeeeffeeeef.
..........fe2222eefffff.
..........f2effff222efff
..........fffeeeffffffff
..........fee44fbe44efef
...........feddfb4d4eef.
..........c.eeddd4eeef..
....ccccccceddee2222f...
.....dddddcedd44e444f...
......ccccc.eeeefffff...
..........c...ffffffff..
...............ff..fff..
........................
........................
........................
........................
........................
........................
........................
........................
`;
            case "image4":
            case "block":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . f f f f f f f f . . . . 
. . . . f f f f f f f f . . . . 
. . . . f f f f f f f f . . . . 
. . . . f f f f f f f f . . . . 
. . . . f f f f f f f f . . . . 
. . . . f f f f f f f f . . . . 
. . . . f f f f f f f f . . . . 
. . . . f f f f f f f f . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "Hero_walking_down":
            case "anim4":return [img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. f f e 2 f f f f f f 2 e f f . 
. f f f f f e e e e f f f f f . 
. . f e f b f 4 4 f b f e f . . 
. . f e 4 1 f d d f 1 4 e f . . 
. . . f e 4 d d d d 4 e f e . . 
. . f e f 2 2 2 2 e d d 4 e . . 
. . e 4 f 2 2 2 2 e d d e . . . 
. . . . f 4 4 5 5 f e e . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f . . . . . . . . . 
`, img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f e e 2 2 2 2 2 2 e f f . . 
. f f e 2 f f f f f f 2 e f f . 
. f f f f f e e e e f f f f f . 
. . f e f b f 4 4 f b f e f . . 
. . f e 4 1 f d d f 1 4 e f . . 
. . e f e 4 d d d d 4 e f . . . 
. . e 4 d d e 2 2 2 2 f e f . . 
. . . e d d e 2 2 2 2 f 4 e . . 
. . . . e e f 5 5 4 4 f . . . . 
. . . . . f f f f f f f . . . . 
. . . . . . . . . f f f . . . . 
`];
            case "Hero_walking_up":
            case "anim2":return [img`
. . . . . . f f f f . . . . . . 
. . . . f f e e e e f f . . . . 
. . . f e e e f f e e e f . . . 
. . f f f f f 2 2 f f f f f . . 
. . f f e 2 e 2 2 e 2 e f f . . 
. . f e 2 f 2 f f 2 f 2 e f . . 
. . f f f 2 2 e e 2 2 f f f . . 
. f f e f 2 f e e f 2 f e f f . 
. f e e f f e e e e f e e e f . 
. . f e e e e e e e e e e f . . 
. . . f e e e e e e e e f . . . 
. . e 4 f f f f f f f f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . f f e e e e f f . . . . 
. . . f e e e f f e e e f . . . 
. . . f f f f 2 2 f f f f . . . 
. . f f e 2 e 2 2 e 2 e f f . . 
. . f e 2 f 2 f f f 2 f e f . . 
. . f f f 2 f e e 2 2 f f f . . 
. . f e 2 f f e e 2 f e e f . . 
. f f e f f e e e f e e e f f . 
. f f e e e e e e e e e e f f . 
. . . f e e e e e e e e f . . . 
. . . e f f f f f f f f 4 e . . 
. . . 4 f 2 2 2 2 2 e d d 4 . . 
. . . e f f f f f f e e 4 . . . 
. . . . f f f . . . . . . . . . 
`, img`
. . . . . . f f f f . . . . . . 
. . . . f f e e e e f f . . . . 
. . . f e e e f f e e e f . . . 
. . f f f f f 2 2 f f f f f . . 
. . f f e 2 e 2 2 e 2 e f f . . 
. . f e 2 f 2 f f 2 f 2 e f . . 
. . f f f 2 2 e e 2 2 f f f . . 
. f f e f 2 f e e f 2 f e f f . 
. f e e f f e e e e f e e e f . 
. . f e e e e e e e e e e f . . 
. . . f e e e e e e e e f . . . 
. . e 4 f f f f f f f f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . f f e e e e f f . . . . 
. . . f e e e f f e e e f . . . 
. . . f f f f 2 2 f f f f . . . 
. . f f e 2 e 2 2 e 2 e f f . . 
. . f e f 2 f f f 2 f 2 e f . . 
. . f f f 2 2 e e f 2 f f f . . 
. . f e e f 2 e e f f 2 e f . . 
. f f e e e f e e e f f e f f . 
. f f e e e e e e e e e e f f . 
. . . f e e e e e e e e f . . . 
. . e 4 f f f f f f f f e . . . 
. . 4 d d e 2 2 2 2 2 f 4 . . . 
. . . 4 e e f f f f f f e . . . 
. . . . . . . . . f f f . . . . 
`];
            case "Hero_Shield_Left":
            case "anim5":return [img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f f . . . . . 
. . . . f 2 f e e e e f f . . . 
. . . f 2 2 2 f e e e e f f . . 
. . . f e e e e f f e e e f . . 
. . f e 2 2 2 2 e e f f f f . . 
. . f 2 e f f f f 2 2 2 e f . . 
. . f f f e e e f f f f f f f . 
. . f e e 4 4 f b e 4 4 e f f . 
. . f f e d d f 1 4 d 4 e e f . 
. f d d f d d d d 4 e e e f . . 
. f b b f e e e 4 e e f . . . . 
. f b b e d d 4 2 2 2 f . . . . 
. . f b e d d e 4 4 4 f f . . . 
. . . f f e e f f f f f f . . . 
. . . . f f f . . . f f . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f f . . . . . 
. . . . f 2 f e e e e f f . . . 
. . . f 2 2 2 f e e e e f f . . 
. . . f e e e e f f e e e f . . 
. . f e 2 2 2 2 e e f f f f . . 
. . f 2 e f f f f 2 2 2 e f . . 
. . f f f e e e f f f f f f f . 
. . f e e 4 4 f b e 4 4 e f f . 
. . . f e d d f 1 4 d 4 e e f . 
. . . . f d d d e e e e e f . . 
. . . . f e 4 e d d 4 f . . . . 
. . . . f 2 2 e d d e f . . . . 
. . . f f 5 5 f e e f f f . . . 
. . . f f f f f f f f f f . . . 
. . . . f f f . . . f f . . . . 
`, img`
. . . . . f f f f f f . . . . . 
. . . . f 2 f e e e e f f . . . 
. . . f 2 2 2 f e e e e f f . . 
. . . f e e e e f f e e e f . . 
. . f e 2 2 2 2 e e f f f f . . 
. . f 2 e f f f f 2 2 2 e f . . 
. . f f f e e e f f f f f f f . 
. . f e e 4 4 f b e 4 4 e f f . 
. . f f e d d f 1 4 d 4 e e f . 
. f d d f d d d d 4 e e e f . . 
. f b b f e e e 4 e e f f . . . 
. f b b e d d 4 2 2 2 f . . . . 
. . f b e d d e 2 2 2 e . . . . 
. . . f f e e f 4 4 4 f . . . . 
. . . . . f f f f f f . . . . . 
. . . . . . . f f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . f f f f f f . . . . . . 
. . . f 2 f e e e e f f . . . . 
. . f 2 2 2 f e e e e f f . . . 
. . f e e e e f f e e e f . . . 
. f e 2 2 2 2 e e f f f f . . . 
. f 2 e f f f f 2 2 2 e f . . . 
. f f f e e e f f f f f f f . . 
. f e e 4 4 f b e 4 4 e f f . . 
. . f e d d f 1 4 d 4 e e f . . 
. . . f d d d e e e e e f . . . 
. . . f e 4 e d d 4 f . . . . . 
. . . f 2 2 e d d e f . . . . . 
. . f f 5 5 f e e f f f . . . . 
. . f f f f f f f f f f . . . . 
. . . f f f . . . f f . . . . . 
`];
            case "Hero_shield_right":
            case "anim6":return [img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f f . . . . . 
. . . f f e e e e f 2 f . . . . 
. . f f e e e e f 2 2 2 f . . . 
. . f e e e f f e e e e f . . . 
. . f f f f e e 2 2 2 2 e f . . 
. . f e 2 2 2 f f f f e 2 f . . 
. f f f f f f f e e e f f f . . 
. f f e 4 4 e b f 4 4 e e f . . 
. f e e 4 d 4 1 f d d e f . . . 
. . f e e e e e d d d f . . . . 
. . . . f 4 d d e 4 e f . . . . 
. . . . f e d d e 2 2 f . . . . 
. . . f f f e e f 5 5 f f . . . 
. . . f f f f f f f f f f . . . 
. . . . f f . . . f f f . . . . 
`, img`
. . . . . f f f f f f . . . . . 
. . . f f e e e e f 2 f . . . . 
. . f f e e e e f 2 2 2 f . . . 
. . f e e e f f e e e e f . . . 
. . f f f f e e 2 2 2 2 e f . . 
. . f e 2 2 2 f f f f e 2 f . . 
. f f f f f f f e e e f f f . . 
. f f e 4 4 e b f 4 4 e e f . . 
. f e e 4 d 4 1 f d d e f f . . 
. . f e e e 4 d d d d f d d f . 
. . . f f e e 4 e e e f b b f . 
. . . . f 2 2 2 4 d d e b b f . 
. . . . e 2 2 2 e d d e b f . . 
. . . . f 4 4 4 f e e f f . . . 
. . . . . f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f f . . . . . 
. . . f f e e e e f 2 f . . . . 
. . f f e e e e f 2 2 2 f . . . 
. . f e e e f f e e e e f . . . 
. . f f f f e e 2 2 2 2 e f . . 
. . f e 2 2 2 f f f f e 2 f . . 
. f f f f f f f e e e f f f . . 
. f f e 4 4 e b f 4 4 e e f . . 
. f e e 4 d 4 1 f d d e f . . . 
. . f e e e e e d d d f . . . . 
. . . . f 4 d d e 4 e f . . . . 
. . . . f e d d e 2 2 f . . . . 
. . . f f f e e f 5 5 f f . . . 
. . . f f f f f f f f f f . . . 
. . . . f f . . . f f f . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f f . . . . . 
. . . f f e e e e f 2 f . . . . 
. . f f e e e e f 2 2 2 f . . . 
. . f e e e f f e e e e f . . . 
. . f f f f e e 2 2 2 2 e f . . 
. . f e 2 2 2 f f f f e 2 f . . 
. f f f f f f f e e e f f f . . 
. f f e 4 4 e b f 4 4 e e f . . 
. f e e 4 d 4 1 f d d e f f . . 
. . f e e e 4 d d d d f d d f . 
. . . . f e e 4 e e e f b b f . 
. . . . f 2 2 2 4 d d e b b f . 
. . . f f 4 4 4 e d d e b f . . 
. . . f f f f f f e e f f . . . 
. . . . f f . . . f f f . . . . 
`];
            case "Hero_walking_right":
            case "anim3":return [img`
. . . . . . f f f f f f . . . . 
. . . . f f e e e e f 2 f . . . 
. . . f f e e e e f 2 2 2 f . . 
. . . f e e e f f e e e e f . . 
. . . f f f f e e 2 2 2 2 e f . 
. . . f e 2 2 2 f f f f e 2 f . 
. . f f f f f f f e e e f f f . 
. . f f e 4 4 e b f 4 4 e e f . 
. . f e e 4 d 4 1 f d d e f . . 
. . . f e e e 4 d d d d f . . . 
. . . . f f e e 4 4 4 e f . . . 
. . . . . 4 d d e 2 2 2 f . . . 
. . . . . e d d e 2 2 2 f . . . 
. . . . . f e e f 4 5 5 f . . . 
. . . . . . f f f f f f . . . . 
. . . . . . . f f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f f f . . . . 
. . . . f f e e e e f 2 f . . . 
. . . f f e e e e f 2 2 2 f . . 
. . . f e e e f f e e e e f . . 
. . . f f f f e e 2 2 2 2 e f . 
. . . f e 2 2 2 f f f f e 2 f . 
. . f f f f f f f e e e f f f . 
. . f f e 4 4 e b f 4 4 e e f . 
. . f e e 4 d 4 1 f d d e f . . 
. . . f e e e e e d d d f . . . 
. . . . . f 4 d d e 4 e f . . . 
. . . . . f e d d e 2 2 f . . . 
. . . . f f f e e f 5 5 f f . . 
. . . . f f f f f f f f f f . . 
. . . . . f f . . . f f f . . . 
`, img`
. . . . . . f f f f f f . . . . 
. . . . f f e e e e f 2 f . . . 
. . . f f e e e e f 2 2 2 f . . 
. . . f e e e f f e e e e f . . 
. . . f f f f e e 2 2 2 2 e f . 
. . . f e 2 2 2 f f f f e 2 f . 
. . f f f f f f f e e e f f f . 
. . f f e 4 4 e b f 4 4 e e f . 
. . f e e 4 d 4 1 f d d e f . . 
. . . f e e e 4 d d d d f . . . 
. . . . f f e e 4 4 4 e f . . . 
. . . . . 4 d d e 2 2 2 f . . . 
. . . . . e d d e 2 2 2 f . . . 
. . . . . f e e f 4 5 5 f . . . 
. . . . . . f f f f f f . . . . 
. . . . . . . f f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f f f . . . . 
. . . . f f e e e e f 2 f . . . 
. . . f f e e e e f 2 2 2 f . . 
. . . f e e e f f e e e e f . . 
. . . f f f f e e 2 2 2 2 e f . 
. . . f e 2 2 2 f f f f e 2 f . 
. . f f f f f f f e e e f f f . 
. . f f e 4 4 e b f 4 4 e e f . 
. . f e e 4 d 4 1 f d d e f . . 
. . . f e e e 4 d d d d f . . . 
. . . . 4 d d e 4 4 4 e f . . . 
. . . . e d d e 2 2 2 2 f . . . 
. . . . f e e f 4 4 5 5 f f . . 
. . . . f f f f f f f f f f . . 
. . . . . f f . . . f f f . . . 
`];
            case "Hero_walking_left":
            case "anim1":return [img`
. . . . f f f f f f . . . . . . 
. . . f 2 f e e e e f f . . . . 
. . f 2 2 2 f e e e e f f . . . 
. . f e e e e f f e e e f . . . 
. f e 2 2 2 2 e e f f f f . . . 
. f 2 e f f f f 2 2 2 e f . . . 
. f f f e e e f f f f f f f . . 
. f e e 4 4 f b e 4 4 e f f . . 
. . f e d d f 1 4 d 4 e e f . . 
. . . f d d d d 4 e e e f . . . 
. . . f e 4 4 4 e e f f . . . . 
. . . f 2 2 2 e d d 4 . . . . . 
. . . f 2 2 2 e d d e . . . . . 
. . . f 5 5 4 f e e f . . . . . 
. . . . f f f f f f . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . f f f f f f . . . . . . 
. . . f 2 f e e e e f f . . . . 
. . f 2 2 2 f e e e e f f . . . 
. . f e e e e f f e e e f . . . 
. f e 2 2 2 2 e e f f f f . . . 
. f 2 e f f f f 2 2 2 e f . . . 
. f f f e e e f f f f f f f . . 
. f e e 4 4 f b e 4 4 e f f . . 
. . f e d d f 1 4 d 4 e e f . . 
. . . f d d d e e e e e f . . . 
. . . f e 4 e d d 4 f . . . . . 
. . . f 2 2 e d d e f . . . . . 
. . f f 5 5 f e e f f f . . . . 
. . f f f f f f f f f f . . . . 
. . . f f f . . . f f . . . . . 
`, img`
. . . . f f f f f f . . . . . . 
. . . f 2 f e e e e f f . . . . 
. . f 2 2 2 f e e e e f f . . . 
. . f e e e e f f e e e f . . . 
. f e 2 2 2 2 e e f f f f . . . 
. f 2 e f f f f 2 2 2 e f . . . 
. f f f e e e f f f f f f f . . 
. f e e 4 4 f b e 4 4 e f f . . 
. . f e d d f 1 4 d 4 e e f . . 
. . . f d d d d 4 e e e f . . . 
. . . f e 4 4 4 e e f f . . . . 
. . . f 2 2 2 e d d 4 . . . . . 
. . . f 2 2 2 e d d e . . . . . 
. . . f 5 5 4 f e e f . . . . . 
. . . . f f f f f f . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . f f f f f f . . . . . . 
. . . f 2 f e e e e f f . . . . 
. . f 2 2 2 f e e e e f f . . . 
. . f e e e e f f e e e f . . . 
. f e 2 2 2 2 e e f f f f . . . 
. f 2 e f f f f 2 2 2 e f . . . 
. f f f e e e f f f f f f f . . 
. f e e 4 4 f b e 4 4 e f f . . 
. . f e d d f 1 4 d 4 e e f . . 
. . . f d d d d 4 e e e f . . . 
. . . f e 4 4 4 e d d 4 . . . . 
. . . f 2 2 2 2 e d d e . . . . 
. . f f 5 5 4 4 f e e f . . . . 
. . f f f f f f f f f f . . . . 
. . . f f f . . . f f . . . . . 
`];
            case "Enemy_walk_left":
            case "anim9":return [img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f1111111df.......
......fd1111111ddf......
......fd111111dddf......
......fd111ddddddf......
......fd1dfbddddbf......
......fbddfcdbbbcf......
.......f11111bbcf.......
.......f1b1fffff........
.......fbfc111bf........
........ff1b1bff........
.........fbfbfff.f......
..........ffffffff......
............fffff.......
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
.........fffff..........
........f11111ff........
.......fb111111bf.......
.......f1111111dbf......
......fd111111dddf......
......fd11111ddddf......
......fd11dddddddf......
......f111dddddddf......
......f11fcddddddf......
.....fb1111bdddbf.......
.....f1b1bdfcfff........
.....fbfbffffffff.......
......fffffffffff.ff....
...........ffffffff.....
........f1b1bffffff.....
........fbfbffffff......
........................
........................
........................
........................
`];
            case "enemy_walk_right":
            case "anim10":return [img`
........................
........................
........................
........................
..........fffff.........
........ff11111f........
.......fb111111bf.......
......fbd1111111f.......
......fddd111111df......
......fdddd11111df......
......fddddddd11df......
......fddddddd111f......
......fddddddcf11f......
.......fbdddb1111bf.....
........fffcfdb1b1f.....
.......ffffffffbfbf.....
....ff.fffffffffff......
.....ffffffff...........
.....ffffffb1b1f........
......ffffffbfbf........
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......fd1111111f.......
......fdd1111111df......
......fddd111111df......
......fdddddd111df......
......fbddddbfd1df......
......fcbbbdcfddbf......
.......fcbb11111f.......
........fffff1b1f.......
........fb111cfbf.......
........ffb1b1ff........
......f.fffbfbf.........
......ffffffff..........
.......fffff............
........................
........................
........................
........................
`];
            case "Enemy_walk_left0":
            case "anim13":return [img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f1111111df.......
......fd1111111ddf......
......fd111111dddf......
......fd111ddddddf......
......fd1dfbddddbf......
......fbddfcdbbbcf......
.......f11111bbcf.......
.......f1b1fffff........
.......fbfc111bf........
........ff1b1bff........
.........fbfbfff.f......
..........ffffffff......
............fffff.......
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
.........fffff..........
........f11111ff........
.......fb111111bf.......
.......f1111111dbf......
......fd111111dddf......
......fd11111ddddf......
......fd11dddddddf......
......f111dddddddf......
......f11fcddddddf......
.....fb1111bdddbf.......
.....f1b1bdfcfff........
.....fbfbffffffff.......
......fffffffffff.ff....
...........ffffffff.....
........f1b1bffffff.....
........fbfbffffff......
........................
........................
........................
........................
`];
            case "Hero_Attack_left":
            case "anim7":return [img`
..............ffffff....
.............f2feeeeff..
............f222feeeeff.
.......cc...feeeeffeeef.
.......cdc.fe2222eeffff.
.......cddcf2effff222ef.
........cddcffeeefffffff
.........cddce44fbe44eff
..........cdceddf14d4eef
..........cccdeddd4eeef.
...........edd4e44eeff..
............ee442222f...
.............f2e2222f...
.............f554444f...
..............ffffff....
................fff.....
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
........................
..............fff.......
.............f2fffff....
...........ff22eeeeeff..
..........ff222eeeeeeff.
..........feeeefffeeeef.
.........fe2222eeefffff.
.........f2efffff222efff
..cc.....fffeeefffffffff
..cdcc...fee44fbbe44efef
..ccddcc..feddfbb4d4eef.
....cdddceefddddd4eeef..
.....ccdcddee2222222f...
......cccdd44e544444f...
.........eeeeffffffff...
.............ff...fff...
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
...............ff.......
.............ff2ffff....
............ff2feeeeff..
...........ff22feeeeeff.
...........feeeeffeeeef.
..........fe2222eefffff.
..........f2effff222efff
..........fffeeeffffffff
..........fee44fbe44efef
...........feddfb4d4eef.
..........c.eeddd4eeef..
....ccccccceddee2222f...
.....dddddcedd44e444f...
......ccccc.eeeefffff...
..........c...ffffffff..
...............ff..fff..
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
..............ffffff....
.............f2feeeeff..
............f222feeeeff.
............feeeeffeeef.
...........fe2222eeffff.
...........f2effff222ef.
...........fffeeefffffff
...........fee44fbe44eff
............feddf14d4eef
.............fdddd4eeef.
.............fe444eddf..
.............ccc22eddf..
.............cdc22fee...
............cddc4444f...
...........cddcfffff....
..........cddc..fff.....
..........cdc...........
..........cc............
........................
........................
........................
........................
........................
........................
`];
            case "Hero_attack_right":
            case "anim8":return [img`
........................
....ffffff..............
..ffeeeef2f....3........
.ffeeeef222f............
.feeeffeeeef...cc.......
.ffffee2222ef.cdc.......
.fe222ffffe2fcddc.......
fffffffeeeffcddc........
ffe44ebf44ecddc.........
fee4d41fddecdc..........
.feee4dddedccc..........
..ffee44e4dde...........
...f222244ee............
...f2222e2f.............
...f444455f.............
....ffffff..............
.....fff................
........................
........................
........................
........................
........................
........................
........................
`, img`
........................
.......fff..............
....fffff2f.............
..ffeeeee22ff...........
.ffeeeeee222ff..........
.feeeefffeeeef..........
.fffffeee2222ef.........
fffe222fffffe2f.........
fffffffffeeefff.....cc..
fefe44ebbf44eef...ccdc..
.fee4d4bbfddef..ccddcc..
..feee4dddddfeecdddc....
...f2222222eeddcdcc.....
...f444445e44ddccc......
...ffffffffeeee.........
...fff...ff.............
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
.......ff...............
....ffff2ff.............
..ffeeeef2ff............
.ffeeeeef22ff...........
.feeeeffeeeef...........
.fffffee2222ef..........
fffe222ffffe2f..........
ffffffffeeefff..........
fefe44ebf44eef..........
.fee4d4bfddef...........
..feee4dddee.c..........
...f2222eeddeccccccc....
...f444e44ddecddddd.....
...fffffeeee.ccccc......
..ffffffff...c..........
..fff..ff...............
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
....ffffff..............
..ffeeeef2f.............
.ffeeeef222f............
.feeeffeeeef............
.ffffee2222ef...........
.fe222ffffe2f...........
fffffffeeefff...........
ffe44ebf44eef...........
fee4d41fddef............
.feee4ddddf.............
..fdde444ef.............
..fdde22ccc.............
...eef22cdc.............
...f4444cddc............
....fffffcddc...........
.....fff..cddc..........
...........cdc..........
............cc..........
........................
........................
........................
........................
........................
........................
`];
            case "enemy_attack_right":
            case "anim12":return [img`
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
......fbd1111111f.......
......fdd1111111df......
......fddd111111df......
......fdddddd111df......
......fdddddd111df......
......fbddddddd1df......
......ffbbddbfd1df......
.......fcbbdcfddbf......
.......fffbddccffff.....
.......ffffcfbbb1bcf....
......ffffffffcd1b1f....
...ffffffffff..fdfdf....
.....ffffff.....f.f.....
........................
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
.........fffff..........
.......ffb1111ff........
......fb1111111bf.......
......f111111111f.......
.....ffff1111111df......
....fb111c1dd111df......
....ffb1b1fdcf11bf......
.....ffbfbfb11111f......
......ffffcfdb1b1f......
.......fcccfcfbfbf......
........ffffffffff......
.........ffffff.........
.........ffffff.........
.....f..fffffff.........
.....fffffffff..........
......fffffff...........
........................
........................
........................
........................
`];
            case "enemy_attack_left":
            case "anim11":return [img`
........................
........................
........................
........................
..........fffff.........
........ff1111bff.......
.......fb1111111bf......
.......f111111111f......
......fd1111111ffff.....
......fd111dd1c111bf....
......fb11fcdf1b1bff....
......f11111bfbfbff.....
......f1b1bdfcffff......
......fbfbfcfcccf.......
......ffffffffff........
.........ffffff.........
.........ffffff.........
.........fffffff..f.....
..........fffffffff.....
...........fffffff......
........................
........................
........................
........................
`, img`
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f1111111dbf......
......fd1111111ddf......
......fd111111dddf......
......fd111ddddddf......
......fd111ddddddf......
......fd1dddddddbf......
......fd1dfbddbbff......
......fbddfcdbbcf.......
.....ffffccddbfff.......
....fcb1bbbfcffff.......
....f1b1dcffffffff......
....fdfdf..ffffffffff...
.....f.f.....ffffff.....
........................
........................
........................
........................
........................
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
